# name of the action
name: reviewdog

# trigger on pull_request events
on:
  pull_request:

# pipeline to execute
jobs:
  diff-review:
    runs-on: ubuntu-latest
    
    steps:
    - name: clone
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

    - name: install go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
      with:
        # use version from go.mod file
        go-version-file: 'go.mod'
        cache: true
        check-latest: true

    - name: golangci-lint
      uses: reviewdog/action-golangci-lint@24d4af2fc93f5b2b296229e8b0c0f658d25707af # v2
      with:
        github_token: ${{ secrets.github_token }}
        golangci_lint_flags: "--config=.golangci.yml"
        fail_on_error: true
        filter_mode: diff_context
        reporter: github-pr-review

  full-review:
    runs-on: ubuntu-latest
    
    steps:
    - name: clone
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

    - name: install go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
      with:
        # use version from go.mod file
        go-version-file: 'go.mod'
        cache: true
        check-latest: true

    - name: golangci-lint
      uses: reviewdog/action-golangci-lint@24d4af2fc93f5b2b296229e8b0c0f658d25707af # v2
      with:
        github_token: ${{ secrets.github_token }}
        golangci_lint_flags: "--config=.golangci.yml"
        fail_on_error: false
        filter_mode: nofilter
